<div class="dashboard-container row">
    <div class="dashboard-secondary col-m-3">
        <div class="dashboard-item">
            <div class="dashboard-item-title"><?=  $escaper->escapeHtml(__('Import Name')) ?></div>
            <?= $escaper->escapeHtml($this->getImport()->getImportName()) ?>
        </div>
        <div class="dashboard-item">
            <div class="dashboard-item-title"><?=  $escaper->escapeHtml(__('Import Type')) ?></div>
            <?= $escaper->escapeHtml($this->getImport()->getType()) ?>
        </div>
        <div class="dashboard-item">
            <div class="dashboard-item-title"><?=  $escaper->escapeHtml(__('Lock Status')) ?></div>
            <?= $escaper->escapeHtml($this->getLockStatus()) ?>
        </div>
        <div class="dashboard-item">
            <div class="dashboard-item-title"><?=  $escaper->escapeHtml(__('Indexers')) ?></div>
            <?= $escaper->escapeHtml(implode(",\n", $this->getImport()->getIndexers())) ?>
        </div>
        <div class="dashboard-item">
            <div class="dashboard-item-title"><?=  $escaper->escapeHtml(__('Report Handlers')) ?></div>
            <?= $escaper->escapeHtml(implode(",\n", $this->getImport()->getReportHandlers())) ?>
        </div>
        <?php if ($this->hasCron()): ?>
            <div class="dashboard-item">
                <div class="dashboard-item-title"><?=  $escaper->escapeHtml(__('Cron')) ?></div>
                <div class="dashboard-item-content">
                    <table class="admin__table-primary">
                        <tbody>
                        <tr>
                            <?php $expression = $this->getCronExpression() ?>
                            <td style="">Expression</td>
                            <td style="" class="last">
                                <?= $escaper->escapeHtml($expression) ?>
                                <br><small><a target="_blank" href="https://crontab.guru/#<?= $escaper->escapeHtml(str_replace(' ', '_', $expression)) ?>">What does that mean?</a></small>
                            </td>
                        </tr>
                        <tr>
                            <td style="">Cron group</td>
                            <td style="" class="last"><?= $escaper->escapeHtml($this->getCronGroup()) ?></td>
                        </tr>
                        <tr>
                            <td style="">Cron code</td>
                            <td style="" class="last"><?= $escaper->escapeHtml($this->getCronCode()) ?></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        <?php endif ?>
    </div>
    <div class="dashboard-secondary col-m-9">
        <?= $this->getChildHtml('type-info') ?>
    </div>
</div>

